#!/bin/bash

# If you use this from crontab, you'll need to set a bunch of environment
# variables you don't normally have to set (since crond doesn't initialize your
# environment by invoking a shell, so you don't have your normal shell profile
# run). Ugh.
#export PYTHONPATH=$HOME/lib/python/
#export PATH=$HOME/bin:$PATH

# Perhaps most annoying for anyone using a modern Linux distribution is
# Python2's default std{in,out,err} codec assumption of ASCII and complete
# inability to listen to reason and let the goddamn distros set something sane.
# So we have to set evironment variables to do this. Because Unicode objects
# are special unicorns and Python devs apparently *mumbles*
export PYTHONIOENCODING=utf8:backslashreplace

# You'll need to set these to something appropriate if you want to use this
# shell script.
WM="^/usr/bin/fluxbox"
TARGET="^rdesktop"
#KEYS="Control_L"
KEYS="Super_L"

python drinking_bird.py "${WM}" "${TARGET}" "${KEYS}" >/dev/null
